stages:
  - lint

services:
  - docker:dind

cache:
  paths:
    - .docker

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: event-bot

before_script:
  - docker info
  - apk add --no-cache make

python-lint:
  stage: lint
  image: python:latest
  before_script:
    - pip install ruff
  script:
    - cd bot
    - ruff check .
  only:
    - merge_requests
    - branches
