services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot_net
    restart: always

  bot:
    build: ./bot
    depends_on:
      - db
    environment:
      TOKEN: ${TOKEN}
      OWNER: ${OWNER}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - bot_net
    restart: always

networks:
  bot_net:
    driver: bridge

volumes:
  db_data:

name: event-bot