x-local: &local
  restart: unless-stopped
  env_file: .env
  environment:
    PYTHONUNBUFFERED: 1
    PYTHONDONTWRITEBYTECODE: 1
  links:
    - database
    - redis
  depends_on:
    database:
      condition: service_healthy
    migrations:
      condition: service_completed_successfully


services:

  bot:
    <<: *local
    container_name: pandito-bot
    build:
      context: .
      dockerfile: Dockerfile

  scheduler:
    <<: *local
    container_name: pandito-scheduler
    build:
      context: .
      dockerfile: ./src/scheduler/Dockerfile

  migrations:
    <<: *local
    container_name: pandito-migrations
    build:
      context: .
      dockerfile: ./src/migrations/Dockerfile
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.4-alpine3.20
    container_name: pandito-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pandito-volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: pandito-redis
    restart: unless-stopped
    volumes:
      - pandito-volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: "redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"

volumes:
  pandito-volume:
