services:

  database:
    image: postgres:16.4-alpine3.20
    container_name: pandito-bot-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    container_name: pandito-bot
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: ./bot/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      TOKEN: ${TOKEN}
      OWNER: ${OWNER}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    links:
      - database

volumes:
  db_data:
