"""quest

Revision ID: 0002
Revises: 0001
Create Date: 2025-01-19 03:58:34.650752

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quests",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=2048), nullable=False),
        sa.Column("task", sa.String(length=1024), nullable=False),
        sa.Column("image_id", sa.String(length=128), nullable=True),
        sa.Column("reward", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(length=128), nullable=False),
        sa.Column("qrcode_image_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quests")),
    )
    op.create_table(
        "users_to_quests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quest_id", sa.String(length=8), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quest_id"],
            ["quests.id"],
            name=op.f("fk_users_to_quests_quest_id_quests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_users_to_quests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "quest_id", name=op.f("pk_users_to_quests")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_to_quests")
    op.drop_table("quests")
    # ### end Alembic commands ###
