"""answer

Revision ID: 0003
Revises: 0002
Create Date: 2025-01-19 06:20:14.825870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quests",
        "answer",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    op.add_column("tasks", sa.Column("answer", sa.String(length=256), nullable=False))
    op.drop_column("tasks", "end_phrase")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "end_phrase",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "answer")
    op.alter_column(
        "quests",
        "answer",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
