"""answer

Revision ID: 0007
Revises: 0006
Create Date: 2025-01-24 18:58:17.178755

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quests",
        "right_answer",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=384),
        existing_nullable=False,
    )
    op.alter_column(
        "quests",
        "wrong_answer",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=384),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quests",
        "wrong_answer",
        existing_type=sa.String(length=384),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "quests",
        "right_answer",
        existing_type=sa.String(length=384),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
