"""index

Revision ID: 0009
Revises: 0008
Create Date: 2025-01-25 01:52:36.291102

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_logs_user_id"), "logs", ["user_id"], unique=False)
    op.drop_constraint("uq_lottery_tickets_user_id", "lottery_tickets", type_="unique")
    op.create_index(
        op.f("ix_lottery_tickets_user_id"),
        "lottery_tickets",
        ["user_id"],
        unique=True,
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_purchases_id"), "purchases", ["id"], unique=False)
    op.create_index(
        op.f("ix_purchases_product_id"),
        "purchases",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchases_user_id"),
        "purchases",
        ["user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_quests_id"), "quests", ["id"], unique=False)
    op.drop_constraint("uq_secrets_phrase", "secrets", type_="unique")
    op.create_index(op.f("ix_secrets_id"), "secrets", ["id"], unique=False)
    op.create_index(op.f("ix_secrets_phrase"), "secrets", ["phrase"], unique=True)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_to_quests_quest_id"),
        "users_to_quests",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_to_quests_user_id"),
        "users_to_quests",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_to_secrets_secret_id"),
        "users_to_secrets",
        ["secret_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_to_secrets_user_id"),
        "users_to_secrets",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_to_tasks_task_id"),
        "users_to_tasks",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_to_tasks_user_id"),
        "users_to_tasks",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_to_tasks_user_id"), table_name="users_to_tasks")
    op.drop_index(op.f("ix_users_to_tasks_task_id"), table_name="users_to_tasks")
    op.drop_index(op.f("ix_users_to_secrets_user_id"), table_name="users_to_secrets")
    op.drop_index(op.f("ix_users_to_secrets_secret_id"), table_name="users_to_secrets")
    op.drop_index(op.f("ix_users_to_quests_user_id"), table_name="users_to_quests")
    op.drop_index(op.f("ix_users_to_quests_quest_id"), table_name="users_to_quests")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_index(op.f("ix_secrets_phrase"), table_name="secrets")
    op.drop_index(op.f("ix_secrets_id"), table_name="secrets")
    op.create_unique_constraint("uq_secrets_phrase", "secrets", ["phrase"])
    op.drop_index(op.f("ix_quests_id"), table_name="quests")
    op.drop_index(op.f("ix_purchases_user_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_product_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_id"), table_name="purchases")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_lottery_tickets_user_id"), table_name="lottery_tickets")
    op.create_unique_constraint(
        "uq_lottery_tickets_user_id",
        "lottery_tickets",
        ["user_id"],
    )
    op.drop_index(op.f("ix_logs_user_id"), table_name="logs")
    # ### end Alembic commands ###
