"""coupons

Revision ID: 0010
Revises: 0009
Create Date: 2025-01-25 15:14:25.367259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
    )
    op.create_table(
        "user_to_coupon",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("coupon_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["coupons.id"],
            name=op.f("fk_user_to_coupon_coupon_id_coupons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_to_coupon_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "coupon_id", name=op.f("pk_user_to_coupon")),
    )
    op.create_index(
        op.f("ix_user_to_coupon_coupon_id"),
        "user_to_coupon",
        ["coupon_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_to_coupon_user_id"),
        "user_to_coupon",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_to_coupon_user_id"), table_name="user_to_coupon")
    op.drop_index(op.f("ix_user_to_coupon_coupon_id"), table_name="user_to_coupon")
    op.drop_table("user_to_coupon")
    op.drop_table("coupons")
    # ### end Alembic commands ###
