"""users

Revision ID: 0011
Revises: 0010
Create Date: 2025-01-25 15:52:52.541612

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=16),
        existing_nullable=True,
    )
    op.drop_constraint("uq_users_tg_id", "users", type_="unique")
    op.create_index(op.f("ix_users_tg_id"), "users", ["tg_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_tg_id"), table_name="users")
    op.create_unique_constraint("uq_users_tg_id", "users", ["tg_id"])
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
